<?php

declare(strict_types=1);

namespace Jascha030\WPECLI;

use RuntimeException;
use Symfony\Component\Filesystem\Filesystem;

use function dirname;
use function sprintf;

/**
 * Test path constants, containing various paths used to setup and validate output generated by commands.
 *
 * @see TEST_OUTPUT_DIR
 * @see TEST_OUTPUT_RELATIVE_PATH
 */

/**
 * Path to the directory that should be generated by create command.
 *
 * @see Create
 * @see Command
 * @see CommandTester
 * @see CreateTest
 */
const TEST_OUTPUT_DIR = __DIR__ . '/../test-output';

/**
 * Path to the directory that should be generated by create command, relative to the package root and working directory.
 *
 * @see TEST_OUTPUT_DIR
 */
const TEST_OUTPUT_RELATIVE_PATH = 'test-output';

/**
 * Require Composers autoloader.
 */
require dirname(__DIR__) . '/vendor/autoload.php';

/**
 * Delete a directory when it exists, to setup clean test environment.
 */
function deleteWhenExists(string $path): void
{
    $fs = new Filesystem();

    if ($fs->exists($path)) {
        $fs->remove($path);
    }
}

(static function (): void {
    namespace\deleteWhenExists(TEST_OUTPUT_DIR);

    if (! mkdir(TEST_OUTPUT_DIR) && ! is_dir(TEST_OUTPUT_DIR)) {
        throw new RuntimeException(sprintf('Directory "%s" was not created', TEST_OUTPUT_DIR));
    }
})();
